name: dragonbones_example
description: Example app drawing a DragonBones animation on a Flutter Canvas.
publish_to: none
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dragonbones_flutter:
    path: ../packages/dragonbones_flutter

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dragon/
    - assets/mecha_1004d/
    - assets/mecha_1004d_show/
    - assets/mecha_1502b/
    - assets/龙/
    
