// Checks that every character bundled with the Flutter example app actually
// loads, and keeps the two generated lists honest.
//
// The example's `assets/` are the repository's own DragonBones fixtures (see
// `test/fixtures/unity/`), copied in as `<name>/ske.json`, `<name>/tex.json`,
// `<name>/tex.png`. Nothing about a fixture being committed proves the *copy*
// is complete, so this tool:
//
//   1. parses each skeleton and atlas with the runtime,
//   2. builds every armature the skeleton declares,
//   3. plays the first animation for a few frames and walks the draw list,
//   4. cross-checks each atlas against its PNG — declared size, and every
//      `SubTexture` region fitting inside the image (a region that does not fit
//      means the app would sample outside the atlas),
//   5. checks that `example/pubspec.yaml` and `example/lib/asset_catalog.dart`
//      list exactly the directories that exist.
//
// Run from the package directory:
//   dart run tool/assets/check_example_assets.dart          # verify
//   dart run tool/assets/check_example_assets.dart --write  # regenerate the lists
import 'dart:convert';
import 'dart:io';

import 'package:dragonbones/dragonbones.dart';

/// Frames to advance each armature before walking its draw list.
const int _frames = 24;

/// A character directory: one skeleton, one atlas, one raster.
class _Character {
  _Character(this.name, this.dir);

  /// Path relative to `example/assets`, with `/` separators.
  final String name;
  final Directory dir;

  File get skeleton => File('${dir.path}/ske.json');
  File get atlas => File('${dir.path}/tex.json');
  File get image => File('${dir.path}/tex.png');
}

/// Locates the repository root by walking up from the current directory.
///
/// The tool runs from `packages/dragonbones`, but nothing stops it from being
/// run from the repository root, so neither is assumed.
Directory _repoRoot() {
  var dir = Directory.current.absolute;
  for (var i = 0; i < 6; i++) {
    if (Directory('${dir.path}/example/assets').existsSync() &&
        Directory('${dir.path}/packages/dragonbones').existsSync()) {
      return dir;
    }
    final parent = dir.parent;
    if (parent.path == dir.path) break;
    dir = parent;
  }
  throw StateError(
    'could not find the repository root from ${Directory.current.path}',
  );
}

/// Every character directory under [assets], sorted, with `/` separators.
List<_Character> _characters(Directory assets) {
  final found = <_Character>[];
  for (final entity in assets.listSync(recursive: true)) {
    if (entity is! Directory) continue;
    final name = entity.path.substring(assets.path.length + 1).replaceAll(Platform.pathSeparator, '/');
    final character = _Character(name, entity);
    if (character.skeleton.existsSync() && character.atlas.existsSync() && character.image.existsSync()) {
      found.add(character);
    }
  }
  found.sort((a, b) => a.name.compareTo(b.name));
  return found;
}

/// Width and height read straight out of a PNG's IHDR chunk.
({int width, int height}) _pngSize(File file) {
  final bytes = file.readAsBytesSync();
  const signature = <int>[0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A];
  if (bytes.length < 24) {
    throw FormatException('${file.path} is too small to be a PNG');
  }
  for (var i = 0; i < signature.length; i++) {
    if (bytes[i] != signature[i]) {
      throw FormatException('${file.path} is not a PNG');
    }
  }
  int be32(int offset) =>
      (bytes[offset] << 24) | (bytes[offset + 1] << 16) | (bytes[offset + 2] << 8) | bytes[offset + 3];
  return (width: be32(16), height: be32(20));
}

String _pubspecHeader(String pubspec) {
  final marker = pubspec.indexOf('\nflutter:\n');
  if (marker < 0) {
    throw StateError('example/pubspec.yaml has no `flutter:` section');
  }
  return pubspec.substring(0, marker + 1);
}

void _writeLists(Directory root, List<_Character> characters) {
  final names = <String>[for (final c in characters) c.name];

  final pubspec = File('${root.path}/example/pubspec.yaml');
  final buffer = StringBuffer(_pubspecHeader(pubspec.readAsStringSync()));
  buffer
    ..writeln('flutter:')
    ..writeln('  uses-material-design: true')
    ..writeln('  assets:');
  for (final name in names) {
    buffer.writeln('    - assets/$name/');
  }
  pubspec.writeAsStringSync(buffer.toString());

  final catalog = File('${root.path}/example/lib/asset_catalog.dart');
  catalog.writeAsStringSync(
    '// GENERATED by tool/assets/check_example_assets.dart --write. Do not edit.\n'
    '//\n'
    '// Every character directory under `assets/`: what the app\'s dropdown\n'
    '// offers and what example/pubspec.yaml must declare. CI fails if the\n'
    '// three disagree.\n'
    '\n'
    '/// Asset directory names, relative to `assets/`.\n'
    'const List<String> kExampleAssets = <String>[\n'
    '${names.map((n) => "  '$n',").join('\n')}\n'
    '];\n',
  );

  print('wrote ${names.length} entries to example/pubspec.yaml and '
      'example/lib/asset_catalog.dart');
}

/// The asset directories declared in `example/pubspec.yaml`.
List<String> _declaredInPubspec(File pubspec) {
  final lines = pubspec.readAsLinesSync();
  final declared = <String>[];
  for (final line in lines) {
    final match = RegExp(r'^\s+- assets/(.+)/\s*$').firstMatch(line);
    if (match != null) declared.add(match.group(1)!);
  }
  return declared;
}

/// The entries of `kExampleAssets` in the generated catalogue.
List<String> _declaredInCatalog(File catalog) {
  return RegExp(r"^\s*'(.+)',\s*$", multiLine: true)
      .allMatches(catalog.readAsStringSync())
      .map((m) => m.group(1)!)
      .toList();
}

void main(List<String> args) {
  final root = _repoRoot();
  final assets = Directory('${root.path}/example/assets');
  final characters = _characters(assets);
  if (characters.isEmpty) {
    throw StateError('no character directories under ${assets.path}');
  }

  if (args.contains('--write')) {
    _writeLists(root, characters);
    return;
  }

  final expected = <String>[for (final c in characters) c.name];
  var failures = 0;
  void fail(String message) {
    failures++;
    print('FAIL $message');
  }

  final declared = _declaredInPubspec(
    File('${root.path}/example/pubspec.yaml'),
  );
  if (declared.join('\n') != expected.join('\n')) {
    fail('example/pubspec.yaml asset list differs from the directories on '
        'disk — run with --write (declared ${declared.length}, '
        'found ${expected.length})');
  }
  final catalogue = _declaredInCatalog(
    File('${root.path}/example/lib/asset_catalog.dart'),
  );
  if (catalogue.join('\n') != expected.join('\n')) {
    fail('example/lib/asset_catalog.dart differs from the directories on '
        'disk — run with --write (listed ${catalogue.length}, '
        'found ${expected.length})');
  }

  var armatureCount = 0;
  var animationCount = 0;
  var drawItems = 0;
  var meshes = 0;
  final withoutAtlasSize = <String>[];

  for (final character in characters) {
    try {
      final factory = HeadlessFactory();
      final data = factory.parseDragonBonesData(
        jsonDecode(character.skeleton.readAsStringSync()),
      );
      if (data == null) {
        fail('${character.name}: skeleton did not parse');
        continue;
      }
      factory.parseTextureAtlasData(
        jsonDecode(character.atlas.readAsStringSync()),
        null,
        data.name,
      );

      // The atlas has to agree with the raster: regions inside the image, and
      // the declared size matching it.
      final png = _pngSize(character.image);
      final atlasJson = jsonDecode(character.atlas.readAsStringSync()) as Map<String, dynamic>;
      final declaredWidth = (atlasJson['width'] as num?)?.toInt();
      final declaredHeight = (atlasJson['height'] as num?)?.toInt();
      if (declaredWidth == null || declaredHeight == null) {
        // Legal, and `weapon_1000` does it: the format allows an atlas that
        // declares no size. The renderer never reads it — it samples the
        // `SubTexture` regions, which the bounds check below covers.
        withoutAtlasSize.add(character.name);
      } else if (declaredWidth != png.width || declaredHeight != png.height) {
        fail('${character.name}: atlas declares '
            '${declaredWidth}x$declaredHeight but the PNG is '
            '${png.width}x${png.height}');
      }
      for (final entry in (atlasJson['SubTexture'] as List? ?? const [])) {
        final sub = entry as Map<String, dynamic>;
        final x = (sub['x'] as num).toInt();
        final y = (sub['y'] as num).toInt();
        final w = (sub['width'] as num).toInt();
        final h = (sub['height'] as num).toInt();
        if (x < 0 || y < 0 || x + w > png.width || y + h > png.height) {
          fail('${character.name}: SubTexture "${sub['name']}" '
              '($x,$y ${w}x$h) falls outside the ${png.width}x${png.height} '
              'atlas');
        }
      }

      if (data.armatureNames.isEmpty) {
        fail('${character.name}: skeleton declares no armature');
        continue;
      }

      var characterDraws = 0;
      for (final armatureName in data.armatureNames) {
        final armature = factory.buildArmature(armatureName, data.name);
        if (armature == null) {
          fail('${character.name}: armature "$armatureName" did not build');
          continue;
        }
        armatureCount++;
        final animations = armature.armatureData.animationNames;
        animationCount += animations.length;
        if (animations.isNotEmpty) {
          armature.animation.play(animations.first);
        }
        for (var frame = 0; frame < _frames; frame++) {
          armature.advanceTime(1.0 / 24.0);
        }
        final list = armature.buildDrawList();
        characterDraws += list.length;
        meshes += list.where((d) => d.mesh != null).length;
      }
      if (characterDraws == 0) {
        fail('${character.name}: every armature drew nothing after $_frames '
            'frames');
      }
      drawItems += characterDraws;
    } on Object catch (error, stack) {
      failures++;
      print('FAIL ${character.name}: $error');
      print('$stack'.split('\n').take(3).join('\n'));
    }
  }

  print('');
  print('$armatureCount armatures, $animationCount animations, '
      '$drawItems draw items ($meshes meshes) over ${characters.length} '
      'characters');
  if (withoutAtlasSize.isNotEmpty) {
    print('note: ${withoutAtlasSize.length} atlas(es) declare no width/height, '
        'which the renderer does not use: ${withoutAtlasSize.join(', ')}');
  }
  if (failures > 0) {
    print('RESULT: FAIL ($failures problems)');
    exit(1);
  }
  print('RESULT: PASS');
}
